### ISSUE TITLE
Receipe 1.4 $AWS_ACCOUNT_ARN to be replaced by $AWS_ACCOUNT_NUM

### ISSUE THREAD

**Issue by GuillaumeHonore** [AWSCookbook/Security#1]
**Describe the bug**
In Receipe 1.4 $AWS_ACCOUNT_ARN is not what needs to be used, instead the account number needs to be used. 

**To Reproduce**
Follow all the steps of the receipe until you reach the validation checks (test the ec2:CreateInternetGateway action)

**Expected behavior**
The account ARN is not the right parameter here so this will fail and return a different error message than in the book. Instead of using the ACCOUNT_ARN I extracted my account number in a new variable I named AWS_ACCOUNT_NUM and it worked.

**Comment by johnculkin** [comment]
Changed AWS_ACCOUNT_ARN to AWS_ACCOUNT_ID
THANKS!
